# Elementwise Operations

## 1. Basic Operations with scalars

In [2]:
import numpy as np
a = np.array([1,2,3,4])

a + 1

array([2, 3, 4, 5])

In [3]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

### All arthematic operates elementwise

In [4]:
b = np.ones(4) + 1

a - b

array([-1.,  0.,  1.,  2.])

In [5]:
a * b

array([2., 4., 6., 8.])

### Matrix multiplication

In [9]:
c = np.diag([1, 2, 3, 4])

print(c * c)
print("******************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
******************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


### comparisons

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])

a == b

array([False,  True, False,  True])

In [11]:
a > b

array([False, False,  True, False])

### Array wise comparisons

In [13]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])

np.array_equal(a,b) #this method is used for comparison of arrays

False

In [14]:
np.array_equal(a,c)

True

### Logical Operations

In [15]:
a = np.array([1,1,0,0])
b = np.array([1,0,1,0])

np.logical_or(a,b) #logical or method for or operation element wise

array([ True,  True,  True, False])

In [17]:
np.logical_and(a,b)

array([ True, False, False, False])

### Trancidental Functions

In [18]:
a = np.arange(5)

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [19]:
np.log(a)

C:\Users\TARUN\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [21]:
np.exp(a) #evaluate e^x

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### Shape mismatch

In [22]:
a = np.arange(4)

a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## 2. Basic Reductions

### Computing sums

In [23]:
x = np.array([1,2,3,4])
np.sum(x)

10

### Sum by rows and by columns

In [24]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [25]:
x.sum(axis=0) #column wise sum

array([3, 3])

In [27]:
x.sum(axis=1) #row wise sum

array([2, 4])

### other reductions

In [28]:
x = np.arange(4)
x.min()

0

In [29]:
x.max()

3

In [30]:
x.argmin() #index of minimum element

0

In [32]:
x.argmax() #index of maximum element

3

### Logical Operations

In [33]:
np.all([True, True, False])

False

In [34]:
np.any([True,False])

True

In [36]:
# can be used for array comparisions
a = np.zeros((50,50))
np.any(a != 0)

False

In [37]:
np.all(a == a)

True

In [38]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all() 

True

### Statistics

In [39]:
x = np.array([1, 2, 3, 1])
y = np.array([[1,2, 3],[5, 6, 1]])
x.mean()

1.75

In [40]:
np.median(x)

1.5

In [41]:
np.median(y, axis=1)

array([2., 5.])

In [43]:
x.std() #full population standard dev

0.82915619758885

##  Loading data

In [44]:
data = np.loadtxt('populations.txt')

In [45]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [46]:
year, hares, lynxes, carrots = data.T #columns to variable
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [47]:
#The population over time
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [48]:
#sample standard deviations
populations.std(axis = 0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [50]:
np.argmax(populations,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

## Broadcasting

Basic Operations on numpy arrays(addition,etc.) are elementwise

This works on arrays of the same size. Neverthless, It's also possible to do operations on arrays of different sizes if Numpy can transform these arrays so that they all have same size: This conversion is called broadcasting.


In [53]:
a = np.tile(np.arange(0,40,10),(3,1))
print(a)
print("*********************")
a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*********************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [55]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [56]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [57]:
a = np.arange(0,40,10)
a.shape

(4,)

In [62]:
a = a[:,np.newaxis] #conversion from 1d array to 2d array
a.shape

(4, 1, 1, 1)

In [63]:
a

array([[[[ 0]]],


       [[[10]]],


       [[[20]]],


       [[[30]]]])

In [64]:
a+b

array([[[[ 0,  1,  2]]],


       [[[10, 11, 12]]],


       [[[20, 21, 22]]],


       [[[30, 31, 32]]]])

### Flattening

In [65]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [66]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

### Reshaping

inverse operation to flattening

In [68]:
print(a.shape)

(2, 3)


In [69]:
print(a)

[[1 2 3]
 [4 5 6]]


In [70]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [72]:
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

### note and beware : reshape may also return a copy:

In [73]:
a = np.zeros((3,2))
b = a.T.reshape(3 * 2)
b[0] = 50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### adding a dimension

Indexin with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimentsion, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D arrau will become 4D array and so on

In [74]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [75]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [76]:
a = np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [77]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [78]:
a[0, 2, 1] 

5

### Resizing

In [79]:
a = np.arange(4)
a.resize((8,))

In [80]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [81]:
b = a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

### Sorting data


In [82]:
a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a,axis=1)

In [83]:
b

array([[4, 5, 6],
       [2, 2, 3]])

### inplace sort

In [84]:
a.sort(axis=1)

In [85]:
a

array([[4, 5, 6],
       [2, 2, 3]])

### Sorting with fancy indexing

In [86]:
a = np.array([4,3,1,2])
j = np.argsort(a)

In [87]:
j

array([2, 3, 1, 0], dtype=int64)

In [88]:
a[j]

array([1, 2, 3, 4])